runtime: python39  # Menggunakan runtime standar untuk hosting HTML statis
service: inventarisasi-fe  # Nama layanan App Engine, bisa diubah sesuai kebutuhan
instance_class: F1  # Kelas instance untuk App Engine (F1 adalah kelas standar yang ringan)

handlers:
  - url: /
    static_files: login.html
    upload: login.html
    
  - url: /
    static_files: barang.html
    upload: barang.html

  - url: /
    static_files: register.html
    upload: register.html


default_expiration: "1h"  # Waktu cache default
